### ISSUE TITLE
[Question] About item events

### ISSUE THREAD

**Issue by V-lpen** [avetharun/FabricDatapackUtils#2]
Can you put conditions on item events?
For example, could I make an "on use" of a sunflower with an NBT tag of "coin"? but trying to "use" a normal sunflower would do nothing?

**Comment by avetharun** [comment]
Technically you can do this via functions, though I will add this! I have a
feature I want to implement next, which is block lights being able to be
dynamically generated.  I'll reply to this when I finish!

**Comment by avetharun** [comment]
@V-lpen Would this be suitable? It supports all nbt tags as well (so count, id, etc.)

https://github.com/avetharun/FabricDatapackUtils/assets/80366076/02a8b660-832a-4bb5-b78a-2b2f8ec1c2d9
